[2025-04-28T13:01:20.863+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-28T13:01:20.885+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scheduler_crawling.crawling_post manual__2025-04-28T13:01:17.624300+00:00 [queued]>
[2025-04-28T13:01:20.896+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scheduler_crawling.crawling_post manual__2025-04-28T13:01:17.624300+00:00 [queued]>
[2025-04-28T13:01:20.899+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-04-28T13:01:20.916+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): crawling_post> on 2025-04-28 13:01:17.624300+00:00
[2025-04-28T13:01:20.932+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1006) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-28T13:01:20.936+0000] {standard_task_runner.py:72} INFO - Started process 1008 to run task
[2025-04-28T13:01:20.937+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scheduler_crawling', 'crawling_post', 'manual__2025-04-28T13:01:17.624300+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/job_post.py', '--cfg-path', '/tmp/tmp269rxz6i']
[2025-04-28T13:01:20.939+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask crawling_post
[2025-04-28T13:01:21.021+0000] {task_command.py:467} INFO - Running <TaskInstance: scheduler_crawling.crawling_post manual__2025-04-28T13:01:17.624300+00:00 [running]> on host 74add6dc246e
[2025-04-28T13:01:21.443+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scheduler_crawling' AIRFLOW_CTX_TASK_ID='crawling_post' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T13:01:17.624300+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T13:01:17.624300+00:00'
[2025-04-28T13:01:21.444+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-28T13:01:21.445+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-28T13:01:21.446+0000] {logging_mixin.py:190} INFO - Current task name:crawling_post state:running start_date:2025-04-28 13:01:20.886435+00:00
[2025-04-28T13:01:21.447+0000] {logging_mixin.py:190} INFO - Dag name:scheduler_crawling and current dag run status:running
[2025-04-28T13:01:21.448+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-28T13:01:21.995+0000] {logging_mixin.py:190} INFO - None
[2025-04-28T13:01:21.996+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/job_post.py", line 44, in get_url
    for i in range(len(response.json()['elements'])):
                       ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'elements'
[2025-04-28T13:01:22.016+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-28T13:01:22.017+0000] {logging_mixin.py:190} INFO - Task start:2025-04-28 13:01:20.886435+00:00 end:2025-04-28 13:01:22.015694+00:00 duration:1.129259
[2025-04-28T13:01:22.018+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): crawling_post> dag:<DAG: scheduler_crawling> dagrun:<DagRun scheduler_crawling @ 2025-04-28 13:01:17.624300+00:00: manual__2025-04-28T13:01:17.624300+00:00, state:running, queued_at: 2025-04-28 13:01:17.668432+00:00. externally triggered: True>
[2025-04-28T13:01:22.019+0000] {logging_mixin.py:190} INFO - Failure caused by 'elements'
[2025-04-28T13:01:22.020+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=scheduler_crawling, task_id=crawling_post, run_id=manual__2025-04-28T13:01:17.624300+00:00, execution_date=20250428T130117, start_date=20250428T130120, end_date=20250428T130122
[2025-04-28T13:01:22.039+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-28T13:01:22.040+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task crawling_post ('elements'; 1008)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/job_post.py", line 44, in get_url
    for i in range(len(response.json()['elements'])):
                       ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'elements'
[2025-04-28T13:01:22.079+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-04-28T13:01:22.342+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T13:01:22.349+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
