[2025-04-28T12:56:24.814+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-28T12:56:24.855+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scheduler_crawling.crawling_post scheduled__2025-04-28T12:30:00+00:00 [queued]>
[2025-04-28T12:56:24.874+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scheduler_crawling.crawling_post scheduled__2025-04-28T12:30:00+00:00 [queued]>
[2025-04-28T12:56:24.876+0000] {taskinstance.py:2856} INFO - Starting attempt 10 of 10
[2025-04-28T12:56:24.906+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): crawling_post> on 2025-04-28 12:30:00+00:00
[2025-04-28T12:56:24.923+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=935) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-28T12:56:24.926+0000] {standard_task_runner.py:72} INFO - Started process 937 to run task
[2025-04-28T12:56:24.926+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scheduler_crawling', 'crawling_post', 'scheduled__2025-04-28T12:30:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/job_post.py', '--cfg-path', '/tmp/tmpny2ldq_e']
[2025-04-28T12:56:24.929+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask crawling_post
[2025-04-28T12:56:25.023+0000] {task_command.py:467} INFO - Running <TaskInstance: scheduler_crawling.crawling_post scheduled__2025-04-28T12:30:00+00:00 [running]> on host 74add6dc246e
[2025-04-28T12:56:25.629+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scheduler_crawling' AIRFLOW_CTX_TASK_ID='crawling_post' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T12:30:00+00:00'
[2025-04-28T12:56:25.634+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-28T12:56:25.638+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-28T12:56:25.641+0000] {logging_mixin.py:190} INFO - Current task name:crawling_post state:running start_date:2025-04-28 12:56:24.857149+00:00
[2025-04-28T12:56:25.643+0000] {logging_mixin.py:190} INFO - Dag name:scheduler_crawling and current dag run status:running
[2025-04-28T12:56:25.648+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-28T12:56:26.208+0000] {logging_mixin.py:190} INFO - {'status': 401, 'serviceErrorCode': 65600, 'code': 'INVALID_ACCESS_TOKEN', 'message': 'Invalid access token'}
[2025-04-28T12:56:26.210+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/job_post.py", line 44, in get_url
    for i in range(len(response.json()['elements'])):
                       ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'elements'
[2025-04-28T12:56:26.234+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-28T12:56:26.236+0000] {logging_mixin.py:190} INFO - Task start:2025-04-28 12:56:24.857149+00:00 end:2025-04-28 12:56:26.234185+00:00 duration:1.377036
[2025-04-28T12:56:26.238+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): crawling_post> dag:<DAG: scheduler_crawling> dagrun:<DagRun scheduler_crawling @ 2025-04-28 12:30:00+00:00: scheduled__2025-04-28T12:30:00+00:00, state:running, queued_at: 2025-04-28 12:56:20.068632+00:00. externally triggered: False>
[2025-04-28T12:56:26.239+0000] {logging_mixin.py:190} INFO - Failure caused by 'elements'
[2025-04-28T12:56:26.241+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=scheduler_crawling, task_id=crawling_post, run_id=scheduled__2025-04-28T12:30:00+00:00, execution_date=20250428T123000, start_date=20250428T125624, end_date=20250428T125626
[2025-04-28T12:56:26.271+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-28T12:56:26.273+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task crawling_post ('elements'; 937)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/job_post.py", line 44, in get_url
    for i in range(len(response.json()['elements'])):
                       ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'elements'
[2025-04-28T12:56:26.313+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-04-28T12:56:26.662+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T12:56:26.676+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
